---
- name: Set go_tarball
  set_fact:
    go_tarball: "go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz"

- name: Ensure go tarball is absent
  file: >
    path=/usr/local/src/{{ go_tarball }}
    state=absent

- name: Ensure go directory is absent
  file: >
    path=/usr/local/go
    state=absent

- name: Download the Go tarball
  get_url: >
    url=http://golang.org/dl/{{ go_tarball }}
    dest=/usr/local/src/{{ go_tarball }}
    sha256sum={{ go_tarball_checksum }}

- name: Extract tarball
  command: tar -C /usr/local -xf /usr/local/src/{{ go_tarball }}

- name: Setup GOPATH
  file: >
    path=/home/deploy/go
    state=directory
    owner=deploy
    group=deploy

- name: Delete go tarball
  file: >
    path=/usr/local/src/{{ go_tarball }}
    state=absent

- name: Install godep
  shell: "GOPATH=/home/deploy/go /usr/local/go/bin/go get github.com/tools/godep"