---
- name: Update APT package cache
  apt: update_cache=yes upgrade=safe

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - apt-transport-https
    - debian-goodies
    - software-properties-common
    - update-notifier-common

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present

- name: Adjust APT update intervals
  copy: >
    src=apt_periodic
    dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  lineinfile: >
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    regexp="$ubuntu_release-updates"
    state=absent