---
- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - ca-certificates
    - curl
    - fail2ban
    - git
    - htop
    - iftop
    - iotop
    - libssl-dev
    - libyaml-dev
    - make
    - mercurial
    - mosh
    - python-software-properties
    - python-virtualenv
    - screen
    - swig
    - tree
    - unzip
    - vim
    - wget
    - zip