---
- name: Add deployment user
  user: >
    name=deploy
    generate_ssh_key=yes
    shell=/bin/bash
    state=present

- name: Add deploy user to sudoers
  lineinfile: >
    dest=/etc/sudoers regexp='deploy ALL'
    line='deploy ALL=(ALL) NOPASSWD: ALL'
    state=present

- name: Create /home/deploy/.ssh
  file: >
    name=/home/deploy/.ssh
    owner=deploy
    group=deploy
    state=directory

- name: Copy authorized_keys
  copy: >
    src=authorized_keys
    dest=/home/deploy/.ssh/authorized_keys
    owner=deploy
    group=deploy
    mode=0400

- name: Remove sudo group rights
  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Disallow password authentication
  lineinfile: >
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present